# Generated by Django 4.2 on 2023-06-16 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customeuser_is_admin_customeuser_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customeuser',
            managers=[
            ],
        ),
    ]
