# Generated by Django 4.2.2 on 2023-06-21 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customeuser_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customeuser',
            name='username',
        ),
    ]
