# Generated by Django 4.2 on 2023-06-12 21:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Playground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('capcity', models.IntegerField(choices=[(5, 5), (7, 7), (11, 11)], default=5)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('grass_type', models.CharField(choices=[('artificial', 'Artificial'), ('natural', 'Natural')], max_length=15)),
                ('image', models.ImageField(upload_to='media')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
