# Generated by Django 4.2 on 2023-06-15 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_playground_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='grass_type',
            field=models.CharField(choices=[('artificial', 'Artificial'), ('natural', 'Natural')], default='artificial', max_length=15),
        ),
    ]
