# Generated by Django 4.2 on 2023-06-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_playground_grass_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='city',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='playground',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
