# Generated by Django 4.2 on 2023-06-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_playground_city_alter_playground_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playground',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='playground',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
