# Generated by Django 4.2 on 2023-06-15 19:57

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_alter_playground_grass_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('start_hour', models.TimeField()),
                ('end_hour', models.TimeField()),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('status', models.CharField(choices=[('free', 'FREE'), ('reserved', 'RESERVED')], default='FREE', help_text='Slot status', max_length=10)),
                ('playground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.playground')),
            ],
            options={
                'unique_together': {('day', 'start_hour', 'end_hour', 'playground')},
            },
        ),
    ]
