# Generated by Django 4.2.2 on 2023-06-18 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('accept', 'accept'), ('reject', 'reject'), ('pending', 'pending')], default='pending', max_length=10),
        ),
    ]
